import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import apiClient from "../api/client";
import SeatMapBuilder from "../components/seatmap/SeatMapBuilder";

export default function EventSeatMapBuilder() {
  const { orgSlug, eventId } = useParams(); const [map, setMap] = useState(null); const [event, setEvent] = useState(null); const [templates, setTemplates] = useState([]); const [error, setError] = useState("");
  useEffect(() => { (async () => { try { const eventResponse = await apiClient.get(`/o/${orgSlug}/events/${eventId}`); const loadedEvent = eventResponse.data.event; setEvent(loadedEvent); const venueId = loadedEvent.venueId?._id || loadedEvent.venueId; const [mapResult, templateResult] = await Promise.allSettled([apiClient.get(`/o/${orgSlug}/events/${eventId}/seatmap`), apiClient.get(`/o/${orgSlug}/venues/${venueId}/seatmaps`)]); if (mapResult.status === "fulfilled") setMap(mapResult.value.data.seatmap); else if (mapResult.reason?.response?.status !== 404) throw mapResult.reason; if (templateResult.status === "fulfilled") setTemplates(templateResult.value.data.seatmaps); else throw templateResult.reason; } catch (err) { setError(err.response?.data?.message || "Could not load event seat map."); } })(); }, [orgSlug, eventId]);
  const save = async (seatmap) => { const { data } = await apiClient.put(`/o/${orgSlug}/events/${eventId}/seatmap`, { seatmap }); setMap(data.seatmap); };
  const seed = async (seatmapId) => { if (map && !window.confirm("Replace the current unsaved layout with this venue template?")) return; const { data } = await apiClient.post(`/o/${orgSlug}/events/${eventId}/seatmap/seed`, { seatmapId }); setMap(data.seatmap); };
  return <div><Link to={`/o/${orgSlug}/manage/events`} className="text-gold-soft">← Back to events</Link>{error && <p className="mt-4 text-danger">{error}</p>}<div className="mt-5 rounded-2xl bg-paper p-5 text-ink-text"><h2 className="font-display text-xl">Venue templates</h2><p className="text-sm text-muted">Templates define layout only. Set ticket prices after selecting a template in this event editor.</p><div className="mt-3 flex flex-wrap gap-2">{templates.map((template) => <button key={template.id} onClick={() => seed(template.id)} className="rounded-lg bg-ink px-4 py-2 text-sm text-paper">Use {template.name}</button>)}{!templates.length && <span className="text-sm text-muted">No saved template for this venue yet.</span>} {!map && <button onClick={() => setMap({ name: event?.name || "Event seating", boundary: { width: 1200, height: 800, color: "#06080d" }, shapes: [], blocks: [], sections: [] })} className="rounded-lg bg-gold px-4 py-2 text-sm font-bold text-ink">Start blank</button>}</div></div>{map && <div className="mt-5"><SeatMapBuilder value={map} onSave={save} eventMode title={`${event?.name || "Event"} seat-map builder`} /></div>}</div>;
}
