import { useEffect, useState } from "react";
import { Bell, Check, ExternalLink, Trash2, X } from "lucide-react";
import { useNavigate } from "react-router-dom";
import apiClient from "../api/client";
export default function MyNotifications({ platform = false }) {
 const [items,setItems]=useState([]);const [loading,setLoading]=useState(true);const [selected,setSelected]=useState(null);const navigate=useNavigate();
 const load=async()=>{setLoading(true);try{const {data}=await apiClient.get("/notifications?limit=50");setItems(data.notifications)}finally{setLoading(false)}};
 useEffect(()=>{load();window.addEventListener("notifications-updated",load);return()=>window.removeEventListener("notifications-updated",load)},[]);
 const action=async(e,item,kind)=>{e.stopPropagation();await apiClient.patch(`/notifications/${item._id}/${kind}`);kind==="dismiss"?setItems(x=>x.filter(n=>n._id!==item._id)):setItems(x=>x.map(n=>n._id===item._id?{...n,readAt:new Date()}:n));window.dispatchEvent(new Event("notifications-updated"))};
 const open=item=>{setSelected(item);if(!item.readAt)action({stopPropagation(){}},item,"read")};
 return <main style={{maxWidth:1000,margin:"0 auto",padding:"52px 32px",color:"#f6f1e7"}}><button onClick={()=>navigate("/browse")} style={{background:"none",border:0,color:"#d5a538",cursor:"pointer"}}>← Back to Browse</button><p style={{color:"#d5a538",letterSpacing:2,fontSize:11}}>MEMBER INBOX</p><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:16}}><h1 style={{fontSize:48,marginTop:0}}>Notifications</h1>{items.length>0&&<button onClick={async()=>{await apiClient.post("/notifications/dismiss-all");setItems([]);window.dispatchEvent(new Event("notifications-updated"))}} style={{border:"1px solid #555a76",background:"transparent",color:"#e1e4ef",padding:"9px 12px",borderRadius:8,cursor:"pointer"}}>Clear all</button>}</div><p style={{color:"#a7abc4",marginBottom:30}}>Your buyer updates and organization activity in one secure inbox.</p>{loading?<p>Loading notifications…</p>:items.length?items.map(item=><article key={item._id} onClick={()=>open(item)} style={{display:"flex",gap:16,padding:20,marginBottom:12,background:item.readAt?"#181b31":"#20243e",border:`1px solid ${item.readAt?"#30344f":"#d5a538"}`,borderRadius:12,cursor:"pointer"}}><Bell color="#d5a538"/><div style={{flex:1}}><b>{item.title}</b>{item.organizationId?.name&&<small style={{marginLeft:8,color:"#b8bdd5"}}>{item.organizationId.name}</small>}<p style={{margin:"6px 0",color:"#c4c8dc"}}>{item.message}</p><small style={{color:"#9197b2"}}>{new Date(item.createdAt).toLocaleString()}</small></div><div><button onClick={e=>action(e,item,"read")} aria-label="Mark read"><Check size={16}/></button><button onClick={e=>action(e,item,"dismiss")} aria-label="Clear"><Trash2 size={16}/></button></div></article>):<p>No active notifications.</p>}{selected&&<div role="dialog" aria-modal="true" onClick={()=>setSelected(null)} style={{position:"fixed",inset:0,zIndex:200,background:"#050610bb",display:"grid",placeItems:"center",padding:20}}><section onClick={e=>e.stopPropagation()} style={{width:"min(520px,100%)",background:"#191c32",border:"1px solid #464a68",borderRadius:15,padding:28,boxShadow:"0 22px 55px #0009"}}><button onClick={()=>setSelected(null)} aria-label="Close" style={{float:"right",background:"none",border:0,color:"#eee"}}><X size={20}/></button><small style={{color:"#d5a538",letterSpacing:1}}>{selected.organizationId?.name||"STAGEPASS"}</small><h2>{selected.title}</h2><p style={{color:"#c8ccdc",lineHeight:1.6}}>{selected.message}</p><p style={{fontSize:12,color:"#9298b4"}}>{new Date(selected.createdAt).toLocaleString()}</p>{selected.link&&<button onClick={()=>navigate(selected.link)} style={{marginTop:14,display:"inline-flex",gap:8,alignItems:"center",padding:"11px 15px",border:0,borderRadius:8,background:"#d5a538",color:"#15172a",fontWeight:800,cursor:"pointer"}}>Open related details <ExternalLink size={16}/></button>}</section></div>}</main>;
}
