import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import apiClient from "../api/client";
import "../components/PlatformAdmin.css";

const money = (value) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 2 }).format(value || 0);
const PlatformOrganizations = () => {
  const [search, setSearch] = useState(""); const [status, setStatus] = useState("all"); const [page, setPage] = useState(1); const [data, setData] = useState(null); const [error, setError] = useState("");
  useEffect(() => { let cancelled = false; const params = new URLSearchParams({ search, status, page: String(page) }); apiClient.get(`/platform-admin/organizations?${params}`).then(({ data }) => !cancelled && setData(data)).catch((err) => !cancelled && setError(err.response?.data?.message || "Could not load organizations.")); return () => { cancelled = true; }; }, [search, status, page]);
  return <><div className="platform-heading"><div><p className="eyebrow">TENANT DIRECTORY</p><h1>Organizations.</h1><p>Cross-platform performance and organization health.</p></div></div><div className="platform-card"><div className="platform-search"><input placeholder="Search organization name or slug" value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} /><select className="platform-filter" value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }}><option value="all">All statuses</option><option value="active">Active</option><option value="suspended">Suspended</option></select></div>{error && <div className="platform-alert">{error}</div>}{!data ? <p className="platform-empty">Loading organizations…</p> : <><table className="platform-table"><thead><tr><th>Organization</th><th>Status</th><th>Members</th><th>Events</th><th>Bookings</th><th>Revenue</th><th /></tr></thead><tbody>{data.organizations.map((org) => <tr key={org._id}><td><strong>{org.name}</strong><br /><small style={{ color: "#9fa2ba" }}>{org.slug}</small></td><td><span className={`platform-badge${org.isSuspended ? " suspended" : ""}`}>{org.isSuspended ? "SUSPENDED" : "ACTIVE"}</span></td><td>{org.memberCount}</td><td>{org.eventCount}</td><td>{org.bookings}</td><td>{money(org.revenue)}</td><td><Link to={`/platform-admin/organizations/${org._id}`}>Inspect →</Link></td></tr>)}{!data.organizations.length && <tr><td colSpan="7" className="platform-empty">No organizations match these filters.</td></tr>}</tbody></table><div style={{ display: "flex", justifyContent: "flex-end", gap: 10, alignItems: "center", marginTop: 18 }}><button className="platform-btn" disabled={data.pagination.page <= 1} onClick={() => setPage((value) => value - 1)}>Previous</button><span style={{ color: "#aeb0c4", fontSize: 13 }}>Page {data.pagination.page} of {data.pagination.pages}</span><button className="platform-btn" disabled={data.pagination.page >= data.pagination.pages} onClick={() => setPage((value) => value + 1)}>Next</button></div></>}</div></>;
};
export default PlatformOrganizations;
