import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import apiClient from "../api/client";
import { cachedGet } from "../api/requestCache";
import SeatMapCanvas from "../components/seatmap/SeatMapCanvas";

export default function SeatSelection() {
  const { orgSlug, eventId } = useParams(); const navigate = useNavigate(); const [map, setMap] = useState(null); const [cart, setCart] = useState({ items: [] }); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const load = async () => { try { const [mapResponse, cartResponse] = await Promise.all([cachedGet(`/o/${orgSlug}/events/${eventId}/seatmap`, 3_000), apiClient.get(`/o/${orgSlug}/cart/${eventId}`)]); setMap(mapResponse.data.seatmap); setCart(cartResponse.data.cart); } catch (err) { setError(err.response?.data?.message || "Could not load this seating plan."); } };
  useEffect(() => { load(); }, [orgSlug, eventId]);
  const selected = useMemo(() => new Set(cart.items.map((item) => `${item.blockId}:${item.seatId}`)), [cart]); const total = cart.items.reduce((sum, item) => sum + Number(item.unitPrice || 0), 0);
  const toggle = async (block, seat) => { if (seat.status !== "available" || busy) return; setBusy(true); try { const exists = selected.has(`${block.id}:${seat.id}`); const response = exists ? await apiClient.delete(`/o/${orgSlug}/cart/${eventId}/seats/${block.id}/${seat.id}`) : await apiClient.post(`/o/${orgSlug}/cart/${eventId}/items`, { blockId: block.id, seatId: seat.id }); setCart(response.data.cart); } catch (err) { setError(err.response?.data?.message || "Could not update your selection."); } finally { setBusy(false); } };
  const changeGaQuantity = async (block, increment) => {
    if (busy) return; const current = cart.items.filter((item) => item.blockId === block.id); const cartSeatIds = new Set(current.map((item) => item.seatId)); const candidate = increment ? block.seats?.find((seat) => seat.status === "available" && !cartSeatIds.has(seat.id)) : current.at(-1);
    if (!candidate) return; setBusy(true); try { const response = increment ? await apiClient.post(`/o/${orgSlug}/cart/${eventId}/items`, { blockId: block.id, seatId: candidate.id }) : await apiClient.delete(`/o/${orgSlug}/cart/${eventId}/seats/${block.id}/${candidate.seatId}`); setCart(response.data.cart); } catch (err) { setError(err.response?.data?.message || "Could not update General Admission quantity."); } finally { setBusy(false); }
  };
  if (!map) return <p className="text-muted">Loading seating plan…</p>;
  return <div className="mx-auto max-w-[1450px]"><Link to={`/o/${orgSlug}/events/${eventId}`} className="text-gold-soft">← Back to event</Link><div className="mt-4 grid gap-5 xl:grid-cols-[1fr_320px]"><section><h1 className="font-display text-3xl text-paper">Choose your seats</h1><div className="mt-3 flex flex-wrap gap-3 text-xs text-paper"><span>● <b className="text-green-400">Available</b></span><span>● <b className="text-gold">Selected</b></span><span>● <b className="text-amber-400">Temporarily held</b></span><span>● <b className="text-slate-400">Sold</b></span><span>● <b className="text-red-400">Organizer hold</b></span></div>{error && <p className="mt-3 rounded-lg bg-red-50 p-3 text-danger">{error}</p>}<SeatMapCanvas map={map} selectedIds={selected} onSeatClick={toggle} onGaClick={(block) => changeGaQuantity(block, true)} className="mt-4" /></section><aside className="h-fit rounded-2xl bg-paper p-5 text-ink-text shadow-xl"><h2 className="font-display text-2xl">Your selection</h2>{map.blocks.filter((block) => block.type === "general-admission").map((block) => { const qty = cart.items.filter((item) => item.blockId === block.id).length; return <div key={block.id} className="mt-3 flex items-center justify-between rounded-lg bg-ink/5 p-3 text-sm"><span>{block.name} · Rs. {block.price || 0}</span><span className="flex gap-2"><button onClick={() => changeGaQuantity(block, false)} disabled={!qty}>−</button><b>{qty}</b><button onClick={() => changeGaQuantity(block, true)}>+</button></span></div>; })}<div className="mt-4 space-y-2">{cart.items.filter((item) => !map.blocks.find((block) => block.id === item.blockId && block.type === "general-admission")).map((item) => <div key={`${item.blockId}:${item.seatId}`} className="flex justify-between border-b border-black/10 pb-2 text-sm"><span>{item.sectionName} · {item.seatName}</span><strong>Rs. {item.unitPrice}</strong></div>)}{!cart.items.length && <p className="text-sm text-muted">Select seats directly on the map.</p>}</div><div className="mt-5 flex justify-between border-t border-black/15 pt-4 font-bold"><span>Total</span><span>Rs. {total}</span></div><button disabled={!cart.items.length} onClick={() => navigate(`/o/${orgSlug}/checkout/${eventId}`)} className="mt-5 w-full rounded-lg bg-gold px-4 py-3 font-bold text-ink disabled:opacity-50">Proceed to payment</button></aside></div></div>;
}
