import { useEffect, useMemo, useRef, useState } from "react";
import SeatMapCanvas from "./SeatMapCanvas";

const uid = (prefix) => `${prefix}-${crypto.randomUUID()}`;
const seats = (rows, cols) => Array.from({ length: rows * cols }, (_, n) => ({ id: uid("seat"), row: Math.floor(n / cols), column: n % cols, seatName: `${String.fromCharCode(65 + Math.floor(n / cols))}${(n % cols) + 1}`, status: "available", type: null }));
const blankMap = () => ({ name: "Untitled seat map", boundary: { width: 1200, height: 800, color: "#dbe3f4" }, shapes: [{ id: uid("shape"), type: "box", label: "STAGE", x: 350, y: 65, width: 500, height: 110, color: "#9000ef", visible: true }], blocks: [], sections: [] });
const block = (type) => ({ id: uid("block"), type, name: type === "general-admission" ? "General Admission" : type === "table" ? "Table section" : "New section", position: { x: 160, y: 260 }, dimensions: type === "general-admission" ? { width: 360, height: 140 } : { width: 330, height: 180 }, configuration: { gap: 30, color: type === "table" ? "#c99a3c" : "#facc15" }, seats: seats(type === "general-admission" ? 1 : type === "table" ? 2 : 6, type === "general-admission" ? 100 : type === "table" ? 4 : 10), price: 0 });

export default function SeatMapBuilder({ value, onSave, eventMode = false, title }) {
  const [map, setMap] = useState(value || blankMap()); const [blockId, setBlockId] = useState(null); const [shapeId, setShapeId] = useState(null); const [mode, setMode] = useState("move"); const [zoom, setZoom] = useState(.8); const [history, setHistory] = useState([]); const [future, setFuture] = useState([]); const [drag, setDrag] = useState(null); const [saving, setSaving] = useState(false); const dirty = useRef(false);
  useEffect(() => { if (value) setMap(value); }, [value]);
  const selectedBlock = useMemo(() => map.blocks.find((item) => item.id === blockId), [map, blockId]); const selectedShape = useMemo(() => map.shapes.find((item) => item.id === shapeId), [map, shapeId]);
  const commit = (fn) => setMap((current) => { setHistory((items) => [...items.slice(-49), current]); setFuture([]); dirty.current = true; return fn(current); });
  const patchBlock = (patch) => commit((current) => ({ ...current, blocks: current.blocks.map((item) => item.id === blockId ? { ...item, ...patch } : item) }));
  const patchShape = (patch) => commit((current) => ({ ...current, shapes: current.shapes.map((item) => item.id === shapeId ? { ...item, ...patch } : item) }));
  const undo = () => setHistory((items) => { const previous = items.at(-1); if (!previous) return items; setFuture((next) => [map, ...next]); setMap(previous); return items.slice(0, -1); });
  const redo = () => setFuture((items) => { const next = items[0]; if (!next) return items; setHistory((old) => [...old, map]); setMap(next); return items.slice(1); });
  const add = (type) => commit((current) => ({ ...current, blocks: [...current.blocks, block(type)] }));
  const addShape = () => { const id = uid("shape"); commit((current) => ({ ...current, shapes: [...current.shapes, { id, type: "box", label: "New label", x: 120, y: 100, width: 200, height: 60, color: "#334155", visible: true }] })); setShapeId(id); setBlockId(null); };
  const beginDrag = (point) => {
    if (mode !== "move") return;
    const shape = [...map.shapes].reverse().find((item) => item.visible !== false && point.x >= item.x && point.x <= item.x + item.width && point.y >= item.y && point.y <= item.y + item.height);
    if (shape) { setShapeId(shape.id); setBlockId(null); setHistory((items) => [...items.slice(-49), map]); setFuture([]); setDrag({ kind: "shape", id: shape.id, start: point, origin: { x: shape.x, y: shape.y } }); return; }
    const foundBlock = [...map.blocks].reverse().find((item) => { const x = item.position?.x || 0; const y = item.position?.y || 0; return point.x >= x - 20 && point.x <= x + (item.dimensions?.width || 340) + 20 && point.y >= y - 20 && point.y <= y + (item.dimensions?.height || 200) + 20; });
    if (foundBlock) { setBlockId(foundBlock.id); setShapeId(null); setHistory((items) => [...items.slice(-49), map]); setFuture([]); setDrag({ kind: "block", id: foundBlock.id, start: point, origin: { ...foundBlock.position } }); }
  };
  const moveDrag = (point) => {
    if (!drag) return;
    const x = Math.max(0, drag.origin.x + point.x - drag.start.x); const y = Math.max(0, drag.origin.y + point.y - drag.start.y);
    setMap((current) => drag.kind === "shape" ? { ...current, shapes: current.shapes.map((item) => item.id === drag.id ? { ...item, x, y } : item) } : { ...current, blocks: current.blocks.map((item) => item.id === drag.id ? { ...item, position: { ...item.position, x, y } } : item) }); dirty.current = true;
  };
  const save = async () => { setSaving(true); try { await onSave(map); dirty.current = false; } finally { setSaving(false); } };
  const editor = selectedShape ? <ShapeEditor shape={selectedShape} patch={patchShape} remove={() => { commit((current) => ({ ...current, shapes: current.shapes.filter((item) => item.id !== shapeId) })); setShapeId(null); }} /> : selectedBlock ? <BlockEditor block={selectedBlock} eventMode={eventMode} patch={patchBlock} remove={() => { commit((current) => ({ ...current, blocks: current.blocks.filter((item) => item.id !== blockId) })); setBlockId(null); }} /> : <CanvasEditor map={map} commit={commit} />;
  return <div className="space-y-4"><header className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-[.18em] text-gold-soft">{eventMode ? "Event pricing & inventory" : "Reusable venue layout"}</p><h1 className="font-display text-3xl text-paper">{title}</h1></div><button onClick={save} disabled={saving} className="rounded-lg bg-gold px-5 py-2.5 font-bold text-ink">{saving ? "Saving…" : "Save / Update"}</button></header>{eventMode && <section className="rounded-2xl bg-paper p-4 text-ink-text"><h2 className="font-display text-xl">Section pricing</h2><p className="text-sm text-muted">Price applies to every seat in that block, table or GA area.</p><div className="mt-3 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{map.blocks.map((item) => <label key={item.id} className="rounded border p-3 text-sm"><b>{item.name}</b><input type="number" min="0" value={item.price ?? 0} onChange={(e) => commit((current) => ({ ...current, blocks: current.blocks.map((x) => x.id === item.id ? { ...x, price: Number(e.target.value) } : x) }))} className="mt-2 w-full rounded border p-2" /></label>)}</div></section>}<nav className="flex flex-wrap gap-2 rounded-xl bg-ink/80 p-2 text-sm"><button onClick={() => setMode("move")} className={`rounded px-3 py-2 ${mode === "move" ? "bg-gold text-ink" : "bg-white/10 text-paper"}`}>Select / move</button><button onClick={() => setMode("seats")} className={`rounded px-3 py-2 ${mode === "seats" ? "bg-gold text-ink" : "bg-white/10 text-paper"}`}>Select seats</button><button onClick={() => add("seat")} className="rounded bg-white/10 px-3 py-2 text-paper">+ Rows</button><button onClick={() => add("table")} className="rounded bg-white/10 px-3 py-2 text-paper">+ Table</button><button onClick={() => add("general-admission")} className="rounded bg-white/10 px-3 py-2 text-paper">+ GA</button><button onClick={addShape} className="rounded bg-white/10 px-3 py-2 text-paper">+ Shape</button><button onClick={undo} className="rounded bg-white/10 px-3 py-2 text-paper">Undo</button><button onClick={redo} className="rounded bg-white/10 px-3 py-2 text-paper">Redo</button><button onClick={() => setZoom((v) => Math.max(.4, v - .1))} className="rounded bg-white/10 px-3 py-2 text-paper">−</button><span className="px-2 py-2 text-paper">{Math.round(zoom * 100)}%</span><button onClick={() => setZoom((v) => Math.min(1.5, v + .1))} className="rounded bg-white/10 px-3 py-2 text-paper">+</button></nav><div className="grid gap-5 xl:grid-cols-[1fr_310px]"><SeatMapCanvas map={map} zoom={zoom} selectedIds={new Set()} selectedShapeId={shapeId} onSeatClick={(item) => { setBlockId(item.id); setShapeId(null); }} onShapeClick={(item) => { setShapeId(item.id); setBlockId(null); }} onPointerDown={beginDrag} onPointerMove={moveDrag} onPointerUp={() => setDrag(null)} /><aside className="rounded-2xl bg-paper p-5 text-ink-text shadow-xl">{editor}</aside></div></div>;
}

const Field = ({ label, value, onChange, type = "text" }) => <label className="block text-sm">{label}<input type={type} value={value} onChange={(e) => onChange(type === "number" ? Number(e.target.value) : e.target.value)} className="mt-1 w-full rounded border p-2" /></label>;
const ShapeEditor = ({ shape, patch, remove }) => <div className="space-y-3"><h2 className="font-display text-xl">Shape details</h2><p className="text-sm text-muted">Use shapes for non-bookable landmarks: entrance, stage, bar, washroom or food area.</p><Field label="Label" value={shape.label || ""} onChange={(label) => patch({ label })} /><Field label="X position" type="number" value={shape.x} onChange={(x) => patch({ x })} /><Field label="Y position" type="number" value={shape.y} onChange={(y) => patch({ y })} /><Field label="Width" type="number" value={shape.width} onChange={(width) => patch({ width })} /><Field label="Height" type="number" value={shape.height} onChange={(height) => patch({ height })} /><label className="block text-sm">Colour<input type="color" value={shape.color} onChange={(e) => patch({ color: e.target.value })} className="mt-1 h-9 w-full" /></label><button onClick={() => patch({ visible: !shape.visible })} className="rounded bg-ink px-3 py-2 text-sm text-paper">{shape.visible === false ? "Show" : "Hide"}</button><button onClick={remove} className="ml-2 text-sm text-danger">Delete shape</button></div>;
const BlockEditor = ({ block, eventMode, patch, remove }) => <div className="space-y-3"><h2 className="font-display text-xl">Block details</h2><Field label="Name" value={block.name} onChange={(name) => patch({ name })} />{eventMode && <Field label="Price (PKR)" type="number" value={block.price || 0} onChange={(price) => patch({ price })} />}<label className="block text-sm">Colour<input type="color" value={block.configuration?.color || "#facc15"} onChange={(e) => patch({ configuration: { ...block.configuration, color: e.target.value } })} className="mt-1 h-9 w-full" /></label><p className="text-sm text-muted">{block.seats?.length || 0} inventory seats</p><button onClick={remove} className="text-sm text-danger">Delete block</button></div>;
const CanvasEditor = ({ map, commit }) => <div className="space-y-3"><h2 className="font-display text-xl">Canvas details</h2><Field label="Map name" value={map.name} onChange={(name) => commit((current) => ({ ...current, name }))} /><label className="block text-sm">Background<input type="color" value={map.boundary?.color || "#dbe3f4"} onChange={(e) => commit((current) => ({ ...current, boundary: { ...current.boundary, color: e.target.value } }))} className="mt-1 h-9 w-full" /></label><p className="text-sm text-muted">Click a block to edit its inventory or a shape to edit the visual landmark.</p></div>;
